version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-cloud-bot
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=your_bot_token
      - ADMIN_ID=your_admin_id
      - CHANNEL_ID=your_channel_id
      - BOT_USERNAME=your_bot_username
    volumes:
      - ./users.json:/app/users.json
